baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "akakshuki docs site"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier="about"
    name="About"
    url="/about/aboutme"
    weight = 3  
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/akakshuki"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
  
[params]
  showPostsOnHomePage = "popular"
  footer = "Copy right Hoang Le"
  enableRobotsTXT = true
  avatarURL = "/images/avt.jpg"
  customPostFootHTML = '''
          <!-- Comments by Cusdis -->
          <h4>Comments:</h4>
          <div id="cusdis_thread" data-host="https://cusdis.com"
            data-app-id="027b3476-7619-49b8-9694-f0f4c591d600"
            data-page-id="{{ .File.UniqueID }}" data-page-url="{{ .Permalink }}"
            data-page-title="{{ .Title }}"></div>
            data-theme="auto"
            <script async defer src="https://cusdis.com/js/cusdis.es.js"></script>
  '''